trigger:
  - none

resources:
  pipelines:
   - pipeline: buildPipeline  # Name of the pipeline resource
     source: 'ETL.App/etl-app_builds' # Name of the triggering pipeline
  repositories:
    - repository: templates
      type: git
      name: 'Frontend - R and D/pipeline-templates'
      ref: master

# Deploy to etl-app_production
stages:
- stage: 'app'
  displayName: 'Deploy to app'

  jobs:
  - deployment:
    displayName: 'Deploying to app'
    environment: etl-app_production
    pool:
      vmImage: windows-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - download: buildPipeline
            artifact: drop
          - task: AzureRmWebAppDeployment@4
            inputs:
              appType: 'webApp'
              azureSubscription: detail-packages-etl_ARM
              deployToSlotOrASE: true
              enableCustomDeployment: true
              AppSettings: '-NODE_ENV production -WEBSITE_NODE_DEFAULT_VERSION ~16'
              ConnectionType: 'AzureRM'
              DeploymentType: webDeploy
              RemoveAdditionalFilesFlag: true
              ResourceGroupName: detail-packages
              SlotName: 'app'
              WebAppName: 'detail-packages-etl'
            env:
              VITE_TRIGGERED_WEBJOBS_API_BASE_URL: $(VITE_TRIGGERED_WEBJOBS_API_BASE_URL)
              DETAIL_WEBJOBS_BASIC_AUTH_USERNAME: $(DETAIL_WEBJOBS_BASIC_AUTH_USERNAME)
              DETAIL_WEBJOBS_BASIC_AUTH_PASSWORD: $(DETAIL_WEBJOBS_BASIC_AUTH_PASSWORD)